GRAPE-19385
ubergrape/grape-ds pull request #51
Opened 2021-01-21 09:47 UTC by AleshaOleg

2021-01-25 13:56 UTC, pseudonymcp requested changes
Link text should have no text decoration (currently has one when href prop is set). Appears in Docusaurus -> improve styling to not be influenced by outside styles.

2021-01-27 15:09 UTC, AleshaOleg commented
Done

2021-01-27 15:50 UTC, pseudonymcp approved these changes
Looks good 👍

2021-01-27 16:13 UTC, sk7 approved these changes

2021-01-27 16:13 UTC, merged