GRAPE-19389
ubergrape/grape-ds pull request #54
Opened 2021-01-21 10:18 UTC by AleshaOleg

2021-01-25 11:29 UTC, pseudonymcp requested changes
The one bug is solved (when members count was shown when members count was 0), but a new one was intrododuced: Now members count other than 0 is not displayed anymore.  

![pseudoshot-0007](https://user-images.githubusercontent.com/1522647/105700267-ea499500-5f08-11eb-92f6-4c8237402a61.png)

2021-01-25 14:17 UTC, AleshaOleg commented
Just fixed it

2021-01-25 14:28 UTC, pseudonymcp approved these changes
Looks good now from the visual side 👍

2021-01-27 13:08 UTC, sk7 approved these changes

2021-01-27 13:08 UTC, merged