GRAPE-19395
ubergrape/grape-ds pull request #61
Opened 2021-01-22 12:34 UTC by AleshaOleg

2021-01-25 13:45 UTC, pseudonymcp requested changes
What's missing is that if a search field is invalid, then the help text has an id the search field can reference to via aria-describedby, and aria-describedby of the search field connects to the error message.

Btw: In Storybook I'm getting an error on the canvas when I try to enter a validationHelp string in the Base story's Controls.


Update:  
- Please check and correct also the font size inside the input.

2021-01-27 14:47 UTC, sk7 commented on web/src/components/text-input/generic.tsx
> +>>>>>>> 1d4b1a305bfa5a84a6d1a09039e149bc34d6a4ae
broken :D

2021-02-01 16:09 UTC, pseudonymcp requested changes
Found some issues:
- font-size inside input is wrong (computed 13.3333px)
- the `necessityIndicator` prop isn't documented: how to define if "required" and "optional" suffix should be shown or hidden? → "A required or optional field can either be denoted with text added to the end of the label or have no indication at all."
- `maxLength` prop should be removed (if it's set it would overlap with the remove-icon)
- `type` prop isn't needed as Search Field has only type=search (is ignored anyway, so please remove it)
- `min` and `max` props should be removed for Search Field as they have no effect and aren't needed

2021-03-03 16:44 UTC, pseudonymcp approved these changes
Looks good now for me 👍

2021-03-03 16:48 UTC, merged